//
//  Refund.swift
//  Stripe
//
//  Created by Jonathan Holland on 8/28/22.
//

import Foundation

public struct Refund: Codable {
    public static let schema = "refunds"

    /// Unique identifier for the object.
    public let id: String
    /// String representing the object's type.
    public let object: String
    /// Amount, in cents.
    public let amount: Int
    /// Balance transaction that describes the impact on your account balance.
    public let balanceTransaction: String?
    /// ID of the charge that was refunded.
    public let charge: String?
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    public let created: TimeInterval
    /// Three-letter ISO currency code, in lowercase.
    public let currency: String
    /// An arbitrary string attached to the object. Often useful for displaying to users.
    public let refundDescription: String?
    /// Provides destination-specific details about the refund (e.g., card, bank transfer).
    public let destinationDetails: DestinationDetails?
    /// After the refund fails, this balance transaction describes the adjustment made on your account balance that reverses the initial balance transaction.
    public let failureBalanceTransaction: String?
    /// Provides the reason for the refund failure.
    public let failureReason: String?
    /// For payment methods without native refund support, email for the customer to receive refund instructions.
    public let instructionsEmail: String?
    /// Set of key-value pairs that you can attach to an object.
    public let metadata: Metadata?
    /// Provides the next action required to complete the refund.
    public let nextAction: NextAction?
    /// ID of the PaymentIntent that was refunded.
    public let paymentIntent: String?
    /// Provides the reason for a refund that is still pending.
    public let pendingReason: PendingReason?
    /// Reason for the refund, either user-provided or generated by Stripe internally.
    public let reason: Reason?
    /// The transaction number that appears on email receipts sent for this refund.
    public let receiptNumber: String?
    /// The transfer reversal that is associated with the refund. Only present if the charge came from another Stripe account.
    public let sourceTransferReversal: String?
    /// Status of the refund.
    public let status: Status?
    /// ID of the invoice this refund is for, if one exists.
    public let invoice: String?
    /// ID of the customer this refund is for, if one exists.
    public let customer: String?
    /// If the accompanying transfer was reversed, the transfer reversal object.
    public let transferReversal: String?

    public init(id: String, object: String, amount: Int, balanceTransaction: String?, charge: String?, created: TimeInterval, currency: String, refundDescription: String?, destinationDetails: DestinationDetails?, failureBalanceTransaction: String?, failureReason: String?, instructionsEmail: String?, metadata: Metadata?, nextAction: NextAction?, paymentIntent: String?, pendingReason: PendingReason?, reason: Reason?, receiptNumber: String?, sourceTransferReversal: String?, status: Status?, transferReversal: String?, invoice: String?, customer: String?) {
        self.id = id
        self.object = object
        self.amount = amount
        self.balanceTransaction = balanceTransaction
        self.charge = charge
        self.created = created
        self.currency = currency
        self.refundDescription = refundDescription
        self.destinationDetails = destinationDetails
        self.failureBalanceTransaction = failureBalanceTransaction
        self.failureReason = failureReason
        self.instructionsEmail = instructionsEmail
        self.metadata = metadata
        self.nextAction = nextAction
        self.paymentIntent = paymentIntent
        self.pendingReason = pendingReason
        self.reason = reason
        self.receiptNumber = receiptNumber
        self.sourceTransferReversal = sourceTransferReversal
        self.status = status
        self.transferReversal = transferReversal
        self.invoice = invoice
        self.customer = customer
    }

    public enum CodingKeys: String, CodingKey {
        case id,
             object,
             amount,
             balanceTransaction = "balance_transaction",
             charge,
             created,
             currency,
             refundDescription = "description",
             destinationDetails = "destination_details",
             failureBalanceTransaction = "failure_balance_transaction",
             failureReason = "failure_reason",
             instructionsEmail = "instructions_email",
             metadata,
             nextAction = "next_action",
             paymentIntent = "payment_intent",
             pendingReason = "pending_reason",
             reason,
             receiptNumber = "receipt_number",
             sourceTransferReversal = "source_transfer_reversal",
             status,
             transferReversal = "transfer_reversal",
             invoice,
             customer
    }

    public enum Reason: String, Codable {
        case duplicate
        case fraudulent
        case requestedByCustomer = "requested_by_customer"
        case expiredUncapturedCharge = "expired_uncaptured_charge"
    }

    public enum Status: String, Codable {
        case pending
        case requiresAction = "requires_action"
        case succeeded
        case failed
        case canceled
    }

    public enum PendingReason: String, Codable {
        case processing
        case insufficientFunds = "insufficient_funds"
        case chargePending = "charge_pending"
    }

    // MARK: - Destination Details
    public struct DestinationDetails: Codable {
        public let card: CardDetails?
        public let type: String

        public init(card: CardDetails?, type: String) {
            self.card = card
            self.type = type
        }

        public struct CardDetails: Codable {
            /// Value of the reference number assigned to the refund.
            public let reference: String?
            /// Status of the reference number on the refund.
            public let referenceStatus: String?
            /// Type of refund attribute method.
            public let referenceType: String?
            /// Type of the refund.
            public let type: String?

            public init(reference: String?, referenceStatus: String?, referenceType: String?, type: String?) {
                self.reference = reference
                self.referenceStatus = referenceStatus
                self.referenceType = referenceType
                self.type = type
            }

            public enum CodingKeys: String, CodingKey {
                case reference,
                     referenceStatus = "reference_status",
                     referenceType = "reference_type",
                     type
            }
        }
    }

    // MARK: - Next Action
    public struct NextAction: Codable {
        /// Contains the refund details.
        public let displayDetails: DisplayDetails?
        /// Type of the next action to perform.
        public let type: String

        public init(displayDetails: DisplayDetails?, type: String) {
            self.displayDetails = displayDetails
            self.type = type
        }

        public enum CodingKeys: String, CodingKey {
            case displayDetails = "display_details",
                 type
        }

        public struct DisplayDetails: Codable {
            public let emailSent: EmailSent?
            public let expiresAt: TimeInterval?

            public init(emailSent: EmailSent?, expiresAt: TimeInterval?) {
                self.emailSent = emailSent
                self.expiresAt = expiresAt
            }

            public enum CodingKeys: String, CodingKey {
                case emailSent = "email_sent",
                     expiresAt = "expires_at"
            }

            public struct EmailSent: Codable {
                public let emailSentAt: TimeInterval
                public let emailSentTo: String

                public init(emailSentAt: TimeInterval, emailSentTo: String) {
                    self.emailSentAt = emailSentAt
                    self.emailSentTo = emailSentTo
                }

                public enum CodingKeys: String, CodingKey {
                    case emailSentAt = "email_sent_at",
                         emailSentTo = "email_sent_to"
                }
            }
        }
    }
}
