//
//  SetupIntent.swift
//  Stripe
//
//  SetupIntent object for saving payment methods without charging.
//

import Foundation

public struct SetupIntent: Codable {
    public static let schema = "setup_intents"

    /// Unique identifier for the object.
    public let id: String
    /// String representing the object's type.
    public let object: String
    /// ID of the Connect application that created the SetupIntent.
    public let application: String?
    /// If present, the SetupIntent's payment method will be attached to the in-context Stripe Account.
    public let attachToSelf: Bool?
    /// Settings for dynamic payment methods compatible with this Setup Intent.
    public let automaticPaymentMethods: AutomaticPaymentMethods?
    /// Reason for cancellation of this SetupIntent.
    public let cancellationReason: CancellationReason?
    /// The client secret of this SetupIntent.
    public let clientSecret: String?
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    public let created: TimeInterval
    /// ID of the Customer this SetupIntent belongs to.
    public let customer: String?
    /// ID of the CustomerAccount this SetupIntent belongs to, if one exists.
    public let customerAccount: String?
    /// An arbitrary string attached to the object.
    public let setupIntentDescription: String?
    /// Payment methods that are specifically excluded from this SetupIntent.
    public let excludedPaymentMethodTypes: [String]?
    /// Indicates the directions of money movement for which this payment method is intended.
    public let flowDirections: [FlowDirection]?
    /// The error encountered in the previous SetupIntent confirmation.
    public let lastSetupError: LastSetupError?
    /// The most recent SetupAttempt for this SetupIntent.
    public let latestAttempt: String?
    /// Has the value `true` if the object exists in live mode.
    public let livemode: Bool
    /// ID of the multi use Mandate generated by the SetupIntent.
    public let mandate: String?
    /// Set of key-value pairs attached to the object.
    public let metadata: Metadata?
    /// If present, this property tells you what actions you need to take.
    public let nextAction: NextAction?
    /// The account on behalf of which to charge.
    public let onBehalfOf: String?
    /// ID of the payment method used with this SetupIntent.
    public let paymentMethod: String?
    /// Information about the payment method configuration.
    public let paymentMethodConfigurationDetails: PaymentMethodConfigurationDetails?
    /// Payment method-specific configuration for this SetupIntent.
    public let paymentMethodOptions: [String: AnyCodable]?
    /// The list of payment method types that this SetupIntent can set up.
    public let paymentMethodTypes: [String]
    /// ID of the single_use Mandate generated by the SetupIntent.
    public let singleUseMandate: String?
    /// Status of this SetupIntent.
    public let status: Status
    /// Indicates how the payment method is intended to be used in the future.
    public let usage: Usage

    public init(id: String, object: String, application: String?, attachToSelf: Bool?, automaticPaymentMethods: AutomaticPaymentMethods?, cancellationReason: CancellationReason?, clientSecret: String?, created: TimeInterval, customer: String?, customerAccount: String?, setupIntentDescription: String?, excludedPaymentMethodTypes: [String]?, flowDirections: [FlowDirection]?, lastSetupError: LastSetupError?, latestAttempt: String?, livemode: Bool, mandate: String?, metadata: Metadata?, nextAction: NextAction?, onBehalfOf: String?, paymentMethod: String?, paymentMethodConfigurationDetails: PaymentMethodConfigurationDetails?, paymentMethodOptions: [String: AnyCodable]?, paymentMethodTypes: [String], singleUseMandate: String?, status: Status, usage: Usage) {
        self.id = id
        self.object = object
        self.application = application
        self.attachToSelf = attachToSelf
        self.automaticPaymentMethods = automaticPaymentMethods
        self.cancellationReason = cancellationReason
        self.clientSecret = clientSecret
        self.created = created
        self.customer = customer
        self.customerAccount = customerAccount
        self.setupIntentDescription = setupIntentDescription
        self.excludedPaymentMethodTypes = excludedPaymentMethodTypes
        self.flowDirections = flowDirections
        self.lastSetupError = lastSetupError
        self.latestAttempt = latestAttempt
        self.livemode = livemode
        self.mandate = mandate
        self.metadata = metadata
        self.nextAction = nextAction
        self.onBehalfOf = onBehalfOf
        self.paymentMethod = paymentMethod
        self.paymentMethodConfigurationDetails = paymentMethodConfigurationDetails
        self.paymentMethodOptions = paymentMethodOptions
        self.paymentMethodTypes = paymentMethodTypes
        self.singleUseMandate = singleUseMandate
        self.status = status
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey {
        case id,
             object,
             application,
             attachToSelf = "attach_to_self",
             automaticPaymentMethods = "automatic_payment_methods",
             cancellationReason = "cancellation_reason",
             clientSecret = "client_secret",
             created,
             customer,
             customerAccount = "customer_account",
             setupIntentDescription = "description",
             excludedPaymentMethodTypes = "excluded_payment_method_types",
             flowDirections = "flow_directions",
             lastSetupError = "last_setup_error",
             latestAttempt = "latest_attempt",
             livemode,
             mandate,
             metadata,
             nextAction = "next_action",
             onBehalfOf = "on_behalf_of",
             paymentMethod = "payment_method",
             paymentMethodConfigurationDetails = "payment_method_configuration_details",
             paymentMethodOptions = "payment_method_options",
             paymentMethodTypes = "payment_method_types",
             singleUseMandate = "single_use_mandate",
             status,
             usage
    }

    // MARK: - Status

    public enum Status: String, Codable {
        case canceled
        case processing
        case requiresAction = "requires_action"
        case requiresConfirmation = "requires_confirmation"
        case requiresPaymentMethod = "requires_payment_method"
        case succeeded
    }

    // MARK: - Cancellation Reason

    public enum CancellationReason: String, Codable {
        case abandoned
        case duplicate
        case requestedByCustomer = "requested_by_customer"
    }

    // MARK: - Usage

    public enum Usage: String, Codable {
        case offSession = "off_session"
        case onSession = "on_session"
    }

    // MARK: - Flow Direction

    public enum FlowDirection: String, Codable {
        case inbound
        case outbound
    }

    // MARK: - Automatic Payment Methods

    public struct AutomaticPaymentMethods: Codable {
        /// Controls whether this SetupIntent will accept redirect-based payment methods.
        public let allowRedirects: AllowRedirects?
        /// Automatically calculates compatible payment methods.
        public let enabled: Bool?

        public init(allowRedirects: AllowRedirects?, enabled: Bool?) {
            self.allowRedirects = allowRedirects
            self.enabled = enabled
        }

        public enum CodingKeys: String, CodingKey {
            case allowRedirects = "allow_redirects",
                 enabled
        }

        public enum AllowRedirects: String, Codable {
            case always
            case never
        }
    }

    // MARK: - Last Setup Error

    public struct LastSetupError: Codable {
        /// For some errors that can be handled programmatically, a short string indicating how to resolve the error.
        public let adviceCode: String?
        /// A code for the error type.
        public let code: String?
        /// A human-readable message providing more details about the error.
        public let message: String?
        /// The type of error returned.
        public let type: ErrorType
        /// A URL for the documentation about this error.
        public let docUrl: String?
        /// The parameter the error relates to.
        public let param: String?
        /// The decline code returned by the network.
        public let declineCode: String?
        /// For card errors resulting from a card issuer decline, a short string indicating how to resolve the error.
        public let networkAdviceCode: String?
        /// For card errors resulting from a card issuer decline, a short string indicating the card network's decline code.
        public let networkDeclineCode: String?
        /// The PaymentMethod object for errors returned on a request involving a PaymentMethod.
        public let paymentMethod: PaymentMethod?
        /// The type of payment method that was used.
        public let paymentMethodType: String?

        public init(adviceCode: String?, code: String?, message: String?, type: ErrorType, docUrl: String?, param: String?, declineCode: String?, networkAdviceCode: String?, networkDeclineCode: String?, paymentMethod: PaymentMethod?, paymentMethodType: String?) {
            self.adviceCode = adviceCode
            self.code = code
            self.message = message
            self.type = type
            self.docUrl = docUrl
            self.param = param
            self.declineCode = declineCode
            self.networkAdviceCode = networkAdviceCode
            self.networkDeclineCode = networkDeclineCode
            self.paymentMethod = paymentMethod
            self.paymentMethodType = paymentMethodType
        }

        public enum CodingKeys: String, CodingKey {
            case adviceCode = "advice_code",
                 code,
                 message,
                 type,
                 docUrl = "doc_url",
                 param,
                 declineCode = "decline_code",
                 networkAdviceCode = "network_advice_code",
                 networkDeclineCode = "network_decline_code",
                 paymentMethod = "payment_method",
                 paymentMethodType = "payment_method_type"
        }

        public enum ErrorType: String, Codable {
            case apiError = "api_error"
            case cardError = "card_error"
            case idempotencyError = "idempotency_error"
            case invalidRequestError = "invalid_request_error"
        }
    }

    // MARK: - Next Action

    public struct NextAction: Codable {
        /// Type of the next action to perform.
        public let type: String
        /// Contains instructions for redirecting the customer.
        public let redirectToUrl: RedirectToUrl?
        /// Contains details for verifying with microdeposits.
        public let verifyWithMicrodeposits: VerifyWithMicrodeposits?

        public init(type: String, redirectToUrl: RedirectToUrl?, verifyWithMicrodeposits: VerifyWithMicrodeposits?) {
            self.type = type
            self.redirectToUrl = redirectToUrl
            self.verifyWithMicrodeposits = verifyWithMicrodeposits
        }

        public enum CodingKeys: String, CodingKey {
            case type,
                 redirectToUrl = "redirect_to_url",
                 verifyWithMicrodeposits = "verify_with_microdeposits"
        }

        public struct RedirectToUrl: Codable {
            /// The URL you must redirect your customer to.
            public let url: String?
            /// The URL the customer will be redirected to after completing the action.
            public let returnUrl: String?

            public init(url: String?, returnUrl: String?) {
                self.url = url
                self.returnUrl = returnUrl
            }

            public enum CodingKeys: String, CodingKey {
                case url,
                     returnUrl = "return_url"
            }
        }

        public struct VerifyWithMicrodeposits: Codable {
            /// The timestamp when the microdeposits are expected to land.
            public let arrivalDate: TimeInterval?
            /// The URL for the hosted verification page.
            public let hostedVerificationUrl: String?
            /// The type of the microdeposit sent to the customer.
            public let microdepositType: MicrodepositType?

            public init(arrivalDate: TimeInterval?, hostedVerificationUrl: String?, microdepositType: MicrodepositType?) {
                self.arrivalDate = arrivalDate
                self.hostedVerificationUrl = hostedVerificationUrl
                self.microdepositType = microdepositType
            }

            public enum CodingKeys: String, CodingKey {
                case arrivalDate = "arrival_date",
                     hostedVerificationUrl = "hosted_verification_url",
                     microdepositType = "microdeposit_type"
            }

            public enum MicrodepositType: String, Codable {
                case amounts
                case descriptorCode = "descriptor_code"
            }
        }
    }

    // MARK: - Payment Method Configuration Details

    public struct PaymentMethodConfigurationDetails: Codable {
        /// ID of the payment method configuration.
        public let id: String
        /// Parent payment method configuration ID.
        public let parent: String?

        public init(id: String, parent: String?) {
            self.id = id
            self.parent = parent
        }
    }
}
